**1. Як можна обробити пропущені значення у DataFrame за допомогою pandas? Наведіть 2 приклади.**

In [ ]:
import numpy as np
import pandas as pd

df = pd.DataFrame(
    dict(
        age=[5, 6, np.nan],
        born=[
            pd.NaT,
            pd.Timestamp("1939-05-27"),
            pd.Timestamp("1940-04-25"),
        ],
        name=["Alfred", "Batman", ""],
        toy=[None, "Batmobile", "Joker"],
    )
)
df

   age       born    name        toy
0  5.0        NaT  Alfred       None
1  6.0 1939-05-27  Batman  Batmobile
2  NaN 1940-04-25              Joker

Створюємо датафрейм з відповідними значеннями пропусків

In [ ]:
df.replace(r'^\s*$', pd.NaT, regex=True).isna()

     age   born   name    toy
0  False   True  False   True
1  False  False  False  False
2   True  False   True  False

Бачимо, в яких клітинках ці значення присутні. Пусті значення не відображаються цією функцією, тому їх шукаємо регексом через реплейс.

In [ ]:
df.replace(r'^\s*$', pd.NaT, regex=True).dropna(subset=["name", "toy"])

   age       born    name        toy
1  6.0 1939-05-27  Batman  Batmobile

Отримуємо відображення копії датафрейму, яка показує тільки fullfilled рядки.

In [ ]:
values = {'age': df['age'].mean(), 'born': 'SomeDay', 'name': 'SomeName', 'toy': 'SomeToy'}
df.replace(r'^\s*$', pd.NaT, regex=True).fillna(value=values)

   age                 born      name        toy
0  5.0              SomeDay    Alfred    SomeToy
1  6.0  1939-05-27 00:00:00    Batman  Batmobile
2  5.5  1940-04-25 00:00:00  SomeName      Joker

Дивимось на копію датафрейму, заповнену вигаданими даними.

**2. Як об'єднати два набори даних у pandas за спільною колонкою?**

---

In [ ]:
df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [1, 2, 3, 5]})
df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
                    'value': [5, 6, 7, 8]})
print(df1)
print('')
print(df2)

  lkey  value
0  foo      1
1  bar      2
2  baz      3
3  foo      5

  rkey  value
0  foo      5
1  bar      6
2  baz      7
3  foo      8

Згідно документацйії створюємо два датафрейми.

In [ ]:
df1.merge(df2, left_on='lkey', right_on='rkey',
          suffixes=('_left', '_right'))

  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  bar           2  bar            6
3  baz           3  baz            7
4  foo           5  foo            5
5  foo           5  foo            8

Отримуємо об'єднаний набір із зрозумілими назвами стовпчиків.

**3. Наведіть два способи виявлення або обробки викидів (outliers) у наборі даних з використанням Python.**

In [ ]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.033497    -0.021905    -0.016209     0.015693
std       1.001052     0.997327     1.004545     1.029130
min      -3.140955    -3.167448    -3.875619    -3.449256
25%      -0.690227    -0.708238    -0.694900    -0.597194
50%      -0.072666     0.001641    -0.032345     0.033729
75%       0.638282     0.651735     0.633219     0.663718
max       3.013810     3.294901     3.459505     4.212492

Згідно прикладу з книги створюємо датафрейм та отримуємо про нього інформацію.

In [ ]:
col = data[2]
col[col.abs() > 3]

199   -3.875619
281   -3.173190
329    3.111975
773    3.459505
783   -3.037965
Name: 2, dtype: float64

Можна подивитись на викиди по стовпчику

In [ ]:
data[(data.abs() > 3).any(axis="columns")]

            0         1         2         3
66  -2.849924 -3.167448 -0.159378  0.546751
171 -0.577836  3.294901 -0.768695 -0.108608
199  0.141655  0.781666 -3.875619  1.614490
281 -1.090976  1.013903 -3.173190 -0.538943
319  0.868997  3.262259  0.744385  0.414683
329 -1.052354 -1.226955  3.111975 -1.706592
541 -3.050189  0.825523 -0.795499  0.982303
554 -2.453532 -0.126030 -0.166427  4.212492
640 -3.106473  0.047391  1.988017 -1.114482
734  3.013810  0.354333 -1.360261 -0.989205
741  0.280997 -2.451480 -1.535188 -3.397342
773  0.125560 -0.876140  3.459505 -0.101129
783  1.200932  1.466028 -3.037965 -0.253385
850 -3.140955  0.061040 -0.241119 -1.605073
946 -1.719302 -0.513023 -0.868951 -3.198143
998 -0.261569  0.270735 -0.746046 -3.449256

*або по всьому датафрейму.

In [ ]:
data[data.abs() > 3] = np.sign(data) * 3
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.033213    -0.022295    -0.015694     0.015525
std       1.000109     0.995042     0.999072     1.021610
min      -3.000000    -3.000000    -3.000000    -3.000000
25%      -0.690227    -0.708238    -0.694900    -0.597194
50%      -0.072666     0.001641    -0.032345     0.033729
75%       0.638282     0.651735     0.633219     0.663718
max       3.000000     3.000000     3.000000     3.000000

Вінзоризуємо дані та дивимось на результат.

**4. Яка різниця між mutable та immutable змінними у Python? Наведіть приклад кожного типу.**

При створенні об'єкта їй присвоюється адреса в пам'яті, якщо ця адреса лишається незмінною при коригуванні об'єкта - він mutable (список, словник, множина). При зміні immutable (int, float, str, tuple) об'єкта створюється новий об'єкт з іншою адресою в пам'яті.

In [ ]:
a_list = ["foo", 2, [4, 5]]
print(f'a_list: {a_list}\na_list_id: {id(a_list)}')
a_list[2] = (3, 4)
print(f'a_list: {a_list}\na_list_id: {id(a_list)}')

a_list: ['foo', 2, [4, 5]]
a_list_id: 139377293253760
a_list: ['foo', 2, (3, 4)]
a_list_id: 139377293253760

In [ ]:
i_int = 1
print(f'i_int: {i_int}\ni_int_id: {id(i_int)}')
i_int += 1
print(f'\ni_int: {i_int}\ni_int_id: {id(i_int)}')

i_float = 1.0
print(f'\ni_float: {i_float}\ni_float_id: {id(i_float)}')
i_float += 1.0
print(f'\ni_float: {i_float}\ni_float_id: {id(i_float)}')

i_str = 'a'
print(f'\ni_str: {i_str}\ni_str_id: {id(i_str)}')
i_str = 'a'*2
print(f'\ni_str: {i_str}\ni_str_id: {id(i_str)}')

i_tupple = (i_int, i_float, i_str)
print(f'\ni_tupple: {i_tupple}\ni_tupple_id: {id(i_tupple)}')
i_tupple = i_tupple*2
print(f'\ni_tupple: {i_tupple}\ni_tupple_id: {id(i_tupple)}')

i_int: 1
i_int_id: 11654376

i_int: 2
i_int_id: 11654408

i_float: 1.0
i_float_id: 139377347409552

i_float: 2.0
i_float_id: 139377290497296

i_str: a
i_str_id: 11716976

i_str: aa
i_str_id: 139378084651024

i_tupple: (2, 2.0, 'aa')
i_tupple_id: 139378203368320

i_tupple: (2, 2.0, 'aa', 2, 2.0, 'aa')
i_tupple_id: 139377290035360

**5. Для чого в Python використовуються функції?**

Функції в Пайтон використовуються для систематизації коду, уникнення повторюваності, ізоляції змінних, полегшення тестування та маштабування.

**6. Чим відрізняється список (list) від множини (set) у Python? Наведіть приклад ситуації, коли set зручніший**

In [ ]:
i_list = [1, 1, 2, 3, 4, 4] #
print(f'i_list: {i_list} - список може містити повтори значень')
print(f'3-й елемент списка i_list: "{i_list[2]}" - у списку є миттєвий доступ до елемента по індексу (список впорядкований)')
i_set = set(i_list) #прибираємо дублікати зі списку, перетворюючи його на множину
print(f'i_set: {i_set} - множина містить тільки унікальні елементи')
i_num = input('Введіть ціле число, щоб миттєво визначити, чи входить воно в множину: ')
print(f'"{i_num}" {"входить в" if int(i_num) in i_set else "не входить в"} множину')

i_list: [1, 1, 2, 3, 4, 4] - список може містити повтори значень
3-й елемент списка i_list: "2" - у списку є миттєвий доступ до елемента по індексу (список впорядкований)
i_set: {1, 2, 3, 4} - множина містить тільки унікальні елементи
Введіть ціле число, щоб миттєво визначити, чи входить воно в множину: 5
"5" не входить в множину

**7. Напишіть приклад використання list comprehension для створення списку квадратів чисел від 1 до 5.**

In [ ]:
[x**2 for x in range(1,6)]

[1, 4, 9, 16, 25]

**8. Що таке groupby() у pandas? Наведіть приклад його використання.**

In [ ]:
df = pd.DataFrame({
                  "key1" : ["a", "a", None, "b", "b", "a", None],
                  "key2" : pd.Series([1, 2, 1, 2, 1, None, 1], dtype="Int64"),
                  "data1" : np.random.standard_normal(7),
                  "data2" : np.random.standard_normal(7)
                  })
df

   key1  key2     data1     data2
0     a     1  1.753948  0.691240
1     a     2 -0.355225  0.362706
2  None     1 -2.029694 -0.778329
3     b     2 -0.292496  0.906865
4     b     1 -0.090001 -2.191891
5     a  <NA> -1.096233 -1.572298
6  None     1 -0.081140  0.413236

In [ ]:
grouped = df["data1"].groupby(df["key1"]) #групуємо дані по ключу key1
grouped.mean() # відображаємо середнє значення згрупованих результатів

key1
a    0.100830
b   -0.191248
Name: data1, dtype: float64

**9. У чому переваги використання бібліотеки NumPy у порівнянні зі звичайними списками Python при роботі з числовими даними?**

Основною перевагою є швидкість обробки даних та зменшений розмір у пам'яті. Python список зберігає кожну змінну окремо з її типом, в Нампі це шматок пам'яті одного типу, тому з використанням цієї бібліотеки можна примінити якусь операцію для зміни одразу всіх елементів (для списків Пайтон потрібно перебирати кожен елемент, щоб його змінити).

**10. Що таке lambda-функція в Python? Наведіть приклад її використання для обчислення квадрата числа. Наведіть приклад її використання у pandas.**

In [ ]:
i_num =lambda x: x**2 #анонімна функція для швидких операцій
print(f"Квадрат введеного числа: {i_num(int(input('Введіть ціле число, щоб миттєво порахувати його квадрат за допомогою лямбда функції: ')))}\n\n")

print('Додаємо до датафрейму стовпчик ознаки позитивності даних для стовпчика "data1":\n')
df['positive'] = df.apply(lambda row: 'yes' if row['data1'] > 0 else 'no', axis = 1)
df.head()

Введіть ціле число, щоб миттєво порахувати його квадрат за допомогою лямбда функції: 56
Квадрат введеного числа: 3136


Додаємо до датафрейму стовпчик ознаки позитивності даних для стовпчика "data1":

   key1  key2     data1     data2 positive
0     a     1  1.753948  0.691240      yes
1     a     2 -0.355225  0.362706       no
2  None     1 -2.029694 -0.778329       no
3     b     2 -0.292496  0.906865       no
4     b     1 -0.090001 -2.191891       no

**11. Як за допомогою pandas обчислити середнє значення по кожній групі в колонці? (припустимо, у вас є колонки, "Товар", "Категорія товару" і "Вартість", обчислити середнє Вартості для кожної Категорії)**

In [ ]:
df.groupby(['Категорія товару'])[['Вартість']].mean() #групуємо по списку стовпчиків (у даному випадку лише один - категорія товару) і змушуємо повернути датафрейм

In [ ]:
df = pd.DataFrame(
    {
        "Animal": ["Falcon", "Falcon", "Parrot", "Parrot"],
        "Max Speed": [380.0, 370.0, 24.0, 26.0],
    }
)
df

   Animal  Max Speed
0  Falcon      380.0
1  Falcon      370.0
2  Parrot       24.0
3  Parrot       26.0

In [ ]:
df.groupby(["Animal"]).mean()

        Max Speed
Animal
Falcon      375.0
Parrot       25.0